version: '3.1'
services:
  # Creating log database service with mongo-db
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports: 
      - ${MONGO_DB_PORT}:27017
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb
      - mongo-db-mongo:/etc/mongo

  # Creating log database explorer with mongo-express
  mongo-db-explorer:
    depends_on:
      - mongo-db
    restart: unless-stopped
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/

  # Application log
  # app:
  #   depends_on:
  #     - mongo-db
  #   build: .
  #   ports: 
  #     - 3000:3000

volumes:
  mongo-db-data:
  mongo-db-config:
  mongo-db-mongo:

